/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.exceptions;

public class EventDaoException extends DaoException
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 6171527831790813097L;

	/**
	 * Method 'EventDaoException'
	 * 
	 * @param message
	 */
	public EventDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'EventDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public EventDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
