/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.exceptions;

public class SensorDaoException extends DaoException
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 4725927987841236637L;

	/**
	 * Method 'SensorDaoException'
	 * 
	 * @param message
	 */
	public SensorDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'SensorDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public SensorDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
