/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.exceptions;

public class TriggerDaoException extends DaoException {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6542323470278909433L;

	/**
	 * Method 'TriggerDaoException'
	 * 
	 * @param message
	 */
	public TriggerDaoException(String message) {
		super(message);
	}

	/**
	 * Method 'TriggerDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public TriggerDaoException(String message, Throwable cause) {
		super(message, cause);
	}

}
