/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collection;

import de.berlin.fu.data.dao.DevicesDao;
import de.berlin.fu.data.dto.Devices;
import de.berlin.fu.data.dto.DevicesPk;
import de.berlin.fu.data.exceptions.DevicesDaoException;

public class DevicesDaoImpl extends AbstractDAO implements DevicesDao {
	/**
	 * The factory class for this DAO has two versions of the create() method -
	 * one that takes no arguments and one that takes a Connection argument. If
	 * the Connection version is chosen then the connection will be stored in
	 * this attribute and will be used by all calls to this DAO, otherwise a new
	 * Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/**
	 * All finder methods in this class use this SELECT constant to build their
	 * queries
	 */
	protected final String SQL_SELECT = "SELECT idDevices FROM "
			+ getTableName() + "";

	/**
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/**
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName()
			+ " ( idDevices ) VALUES ( ? )";

	/**
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName()
			+ " SET idDevices = ? WHERE idDevices = ?";

	/**
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName()
			+ " WHERE idDevices = ?";

	/**
	 * Index of column idDevices
	 */
	protected static final int COLUMN_ID_DEVICES = 1;

	/**
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 1;

	/**
	 * Index of primary-key column idDevices
	 */
	protected static final int PK_COLUMN_ID_DEVICES = 1;

	/**
	 * Inserts a new row in the Devices table.
	 */
	public DevicesPk insert(Devices dto) throws DevicesDaoException {
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			stmt = conn.prepareStatement(SQL_INSERT,
					Statement.RETURN_GENERATED_KEYS);
			int index = 1;
			stmt.setInt(index++, dto.getIdDevices());
			System.out.println("Executing " + SQL_INSERT + " with DTO: " + dto);
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");

			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdDevices(rs.getInt(1));
			}

			reset(dto);
			return dto.createPk();
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new DevicesDaoException("Exception: " + _e.getMessage(), _e);
		} finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Updates a single row in the Devices table.
	 */
	public void update(DevicesPk pk, Devices dto) throws DevicesDaoException {
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			System.out.println("Executing " + SQL_UPDATE + " with DTO: " + dto);
			stmt = conn.prepareStatement(SQL_UPDATE);
			int index = 1;
			stmt.setInt(index++, dto.getIdDevices());
			stmt.setInt(2, pk.getIdDevices());
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new DevicesDaoException("Exception: " + _e.getMessage(), _e);
		} finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Deletes a single row in the Devices table.
	 */
	public void delete(DevicesPk pk) throws DevicesDaoException {
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			System.out.println("Executing " + SQL_DELETE + " with PK: " + pk);
			stmt = conn.prepareStatement(SQL_DELETE);
			stmt.setInt(1, pk.getIdDevices());
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new DevicesDaoException("Exception: " + _e.getMessage(), _e);
		} finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Returns the rows from the Devices table that matches the specified
	 * primary-key value.
	 */
	public Devices findByPrimaryKey(DevicesPk pk) throws DevicesDaoException {
		return findByPrimaryKey(pk.getIdDevices());
	}

	/**
	 * Returns all rows from the Devices table that match the criteria
	 * 'idDevices = :idDevices'.
	 */
	public Devices findByPrimaryKey(int idDevices) throws DevicesDaoException {
		Devices ret[] = findByDynamicSelect(
				SQL_SELECT + " WHERE idDevices = ?",
				new Object[] { new Integer(idDevices) });
		return ret.length == 0 ? null : ret[0];
	}

	/**
	 * Returns all rows from the Devices table that match the criteria ''.
	 */
	public Devices[] findAll() throws DevicesDaoException {
		return findByDynamicSelect(SQL_SELECT + " ORDER BY idDevices", null);
	}

	/**
	 * Returns all rows from the Devices table that match the criteria
	 * 'idDevices = :idDevices'.
	 */
	public Devices[] findWhereIdDevicesEquals(int idDevices)
			throws DevicesDaoException {
		return findByDynamicSelect(SQL_SELECT
				+ " WHERE idDevices = ? ORDER BY idDevices",
				new Object[] { new Integer(idDevices) });
	}

	/**
	 * Method 'DevicesDaoImpl'
	 * 
	 */
	public DevicesDaoImpl() {
	}

	/**
	 * Method 'DevicesDaoImpl'
	 * 
	 * @param userConn
	 */
	public DevicesDaoImpl(final java.sql.Connection userConn) {
		this.userConn = userConn;
	}

	/**
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows) {
		this.maxRows = maxRows;
	}

	/**
	 * Gets the value of maxRows
	 */
	public int getMaxRows() {
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName() {
		return "telpro.Devices";
	}

	/**
	 * Fetches a single row from the result set
	 */
	protected Devices fetchSingleResult(ResultSet rs) throws SQLException {
		if (rs.next()) {
			Devices dto = new Devices();
			populateDto(dto, rs);
			return dto;
		} else {
			return null;
		}

	}

	/**
	 * Fetches multiple rows from the result set
	 */
	protected Devices[] fetchMultiResults(ResultSet rs) throws SQLException {
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Devices dto = new Devices();
			populateDto(dto, rs);
			resultList.add(dto);
		}

		Devices ret[] = new Devices[resultList.size()];
		resultList.toArray(ret);
		return ret;
	}

	/**
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Devices dto, ResultSet rs) throws SQLException {
		dto.setIdDevices(rs.getInt(COLUMN_ID_DEVICES));
	}

	/**
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Devices dto) {
	}

	/**
	 * Returns all rows from the Devices table that match the specified
	 * arbitrary SQL statement
	 */
	public Devices[] findByDynamicSelect(String sql, Object[] sqlParams)
			throws DevicesDaoException {
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			// construct the SQL statement
			final String SQL = sql;

			System.out.println("Executing " + SQL);
			// prepare statement
			stmt = conn.prepareStatement(SQL);
			stmt.setMaxRows(maxRows);

			// bind parameters
			for (int i = 0; sqlParams != null && i < sqlParams.length; i++) {
				stmt.setObject(i + 1, sqlParams[i]);
			}

			rs = stmt.executeQuery();

			// fetch the results
			return fetchMultiResults(rs);
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new DevicesDaoException("Exception: " + _e.getMessage(), _e);
		} finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Returns all rows from the Devices table that match the specified
	 * arbitrary SQL statement
	 */
	public Devices[] findByDynamicWhere(String sql, Object[] sqlParams)
			throws DevicesDaoException {
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;

			System.out.println("Executing " + SQL);
			// prepare statement
			stmt = conn.prepareStatement(SQL);
			stmt.setMaxRows(maxRows);

			// bind parameters
			for (int i = 0; sqlParams != null && i < sqlParams.length; i++) {
				stmt.setObject(i + 1, sqlParams[i]);
			}

			rs = stmt.executeQuery();

			// fetch the results
			return fetchMultiResults(rs);
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new DevicesDaoException("Exception: " + _e.getMessage(), _e);
		} finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

}
