/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collection;

import de.berlin.fu.data.dao.PropertyTypeDao;
import de.berlin.fu.data.dto.PropertyType;
import de.berlin.fu.data.dto.PropertyTypePk;
import de.berlin.fu.data.exceptions.PropertyTypeDaoException;

public class PropertyTypeDaoImpl extends AbstractDAO implements PropertyTypeDao {
	/**
	 * The factory class for this DAO has two versions of the create() method -
	 * one that takes no arguments and one that takes a Connection argument. If
	 * the Connection version is chosen then the connection will be stored in
	 * this attribute and will be used by all calls to this DAO, otherwise a new
	 * Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/**
	 * All finder methods in this class use this SELECT constant to build their
	 * queries
	 */
	protected final String SQL_SELECT = "SELECT idPropertyType, Name FROM "
			+ getTableName() + "";

	/**
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/**
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName()
			+ " ( idPropertyType, Name ) VALUES ( ?, ? )";

	/**
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName()
			+ " SET idPropertyType = ?, Name = ? WHERE idPropertyType = ?";

	/**
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName()
			+ " WHERE idPropertyType = ?";

	/**
	 * Index of column idPropertyType
	 */
	protected static final int COLUMN_ID_PROPERTY_TYPE = 1;

	/**
	 * Index of column Name
	 */
	protected static final int COLUMN_NAME = 2;

	/**
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/**
	 * Index of primary-key column idPropertyType
	 */
	protected static final int PK_COLUMN_ID_PROPERTY_TYPE = 1;

	/**
	 * Inserts a new row in the PropertyType table.
	 */
	public PropertyTypePk insert(PropertyType dto)
			throws PropertyTypeDaoException {
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			stmt = conn.prepareStatement(SQL_INSERT,
					Statement.RETURN_GENERATED_KEYS);
			int index = 1;
			stmt.setInt(index++, dto.getIdPropertyType());
			stmt.setString(index++, dto.getName());
			System.out.println("Executing " + SQL_INSERT + " with DTO: " + dto);
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");

			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdPropertyType(rs.getInt(1));
			}

			reset(dto);
			return dto.createPk();
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new PropertyTypeDaoException("Exception: " + _e.getMessage(),
					_e);
		} finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Updates a single row in the PropertyType table.
	 */
	public void update(PropertyTypePk pk, PropertyType dto)
			throws PropertyTypeDaoException {
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			System.out.println("Executing " + SQL_UPDATE + " with DTO: " + dto);
			stmt = conn.prepareStatement(SQL_UPDATE);
			int index = 1;
			stmt.setInt(index++, dto.getIdPropertyType());
			stmt.setString(index++, dto.getName());
			stmt.setInt(3, pk.getIdPropertyType());
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new PropertyTypeDaoException("Exception: " + _e.getMessage(),
					_e);
		} finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Deletes a single row in the PropertyType table.
	 */
	public void delete(PropertyTypePk pk) throws PropertyTypeDaoException {
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			System.out.println("Executing " + SQL_DELETE + " with PK: " + pk);
			stmt = conn.prepareStatement(SQL_DELETE);
			stmt.setInt(1, pk.getIdPropertyType());
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println(rows + " rows affected (" + (t2 - t1) + " ms)");
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new PropertyTypeDaoException("Exception: " + _e.getMessage(),
					_e);
		} finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Returns the rows from the PropertyType table that matches the specified
	 * primary-key value.
	 */
	public PropertyType findByPrimaryKey(PropertyTypePk pk)
			throws PropertyTypeDaoException {
		return findByPrimaryKey(pk.getIdPropertyType());
	}

	/**
	 * Returns all rows from the PropertyType table that match the criteria
	 * 'idPropertyType = :idPropertyType'.
	 */
	public PropertyType findByPrimaryKey(int idPropertyType)
			throws PropertyTypeDaoException {
		PropertyType ret[] = findByDynamicSelect(SQL_SELECT
				+ " WHERE idPropertyType = ?",
				new Object[] { Integer.valueOf(idPropertyType) });
		return ret.length == 0 ? null : ret[0];
	}

	/**
	 * Returns all rows from the PropertyType table that match the criteria ''.
	 */
	public PropertyType[] findAll() throws PropertyTypeDaoException {
		return findByDynamicSelect(SQL_SELECT + " ORDER BY idPropertyType",
				null);
	}

	/**
	 * Returns all rows from the PropertyType table that match the criteria
	 * 'idPropertyType = :idPropertyType'.
	 */
	public PropertyType[] findWhereIdPropertyTypeEquals(int idPropertyType)
			throws PropertyTypeDaoException {
		return findByDynamicSelect(SQL_SELECT
				+ " WHERE idPropertyType = ? ORDER BY idPropertyType",
				new Object[] { Integer.valueOf(idPropertyType) });
	}

	/**
	 * Returns all rows from the PropertyType table that match the criteria
	 * 'Name = :name'.
	 */
	public PropertyType[] findWhereNameEquals(String name)
			throws PropertyTypeDaoException {
		return findByDynamicSelect(
				SQL_SELECT + " WHERE Name = ? ORDER BY Name",
				new Object[] { name });
	}

	/**
	 * Method 'PropertyTypeDaoImpl'
	 * 
	 */
	public PropertyTypeDaoImpl() {
	}

	/**
	 * Method 'PropertyTypeDaoImpl'
	 * 
	 * @param userConn
	 */
	public PropertyTypeDaoImpl(final java.sql.Connection userConn) {
		this.userConn = userConn;
	}

	/**
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows) {
		this.maxRows = maxRows;
	}

	/**
	 * Gets the value of maxRows
	 */
	public int getMaxRows() {
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName() {
		return "telpro.PropertyType";
	}

	/**
	 * Fetches a single row from the result set
	 */
	protected PropertyType fetchSingleResult(ResultSet rs) throws SQLException {
		if (rs.next()) {
			PropertyType dto = new PropertyType();
			populateDto(dto, rs);
			return dto;
		} else {
			return null;
		}

	}

	/**
	 * Fetches multiple rows from the result set
	 */
	protected PropertyType[] fetchMultiResults(ResultSet rs)
			throws SQLException {
		Collection<PropertyType> resultList = new ArrayList<PropertyType>();
		while (rs.next()) {
			PropertyType dto = new PropertyType();
			populateDto(dto, rs);
			resultList.add(dto);
		}

		PropertyType ret[] = new PropertyType[resultList.size()];
		resultList.toArray(ret);
		return ret;
	}

	/**
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PropertyType dto, ResultSet rs)
			throws SQLException {
		dto.setIdPropertyType(rs.getInt(COLUMN_ID_PROPERTY_TYPE));
		dto.setName(rs.getString(COLUMN_NAME));
	}

	/**
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PropertyType dto) {
	}

	/**
	 * Returns all rows from the PropertyType table that match the specified
	 * arbitrary SQL statement
	 */
	public PropertyType[] findByDynamicSelect(String sql, Object[] sqlParams)
			throws PropertyTypeDaoException {
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			// construct the SQL statement
			final String SQL = sql;

			System.out.println("Executing " + SQL);
			// prepare statement
			stmt = conn.prepareStatement(SQL);
			stmt.setMaxRows(maxRows);

			// bind parameters
			for (int i = 0; sqlParams != null && i < sqlParams.length; i++) {
				stmt.setObject(i + 1, sqlParams[i]);
			}

			rs = stmt.executeQuery();

			// fetch the results
			return fetchMultiResults(rs);
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new PropertyTypeDaoException("Exception: " + _e.getMessage(),
					_e);
		} finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

	/**
	 * Returns all rows from the PropertyType table that match the specified
	 * arbitrary SQL statement
	 */
	public PropertyType[] findByDynamicWhere(String sql, Object[] sqlParams)
			throws PropertyTypeDaoException {
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;

		try {
			// get the user-specified connection or get a connection from the
			// ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();

			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;

			System.out.println("Executing " + SQL);
			// prepare statement
			stmt = conn.prepareStatement(SQL);
			stmt.setMaxRows(maxRows);

			// bind parameters
			for (int i = 0; sqlParams != null && i < sqlParams.length; i++) {
				stmt.setObject(i + 1, sqlParams[i]);
			}

			rs = stmt.executeQuery();

			// fetch the results
			return fetchMultiResults(rs);
		} catch (Exception _e) {
			_e.printStackTrace();
			throw new PropertyTypeDaoException("Exception: " + _e.getMessage(),
					_e);
		} finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}

		}

	}

}
