/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import de.berlin.fu.data.dao.DevicesDao;
import de.berlin.fu.data.dto.Devices;
import de.berlin.fu.data.exceptions.DevicesDaoException;
import de.berlin.fu.data.factory.DevicesDaoFactory;

public class DevicesDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdDevicesEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DevicesDao _dao = getDevicesDao();
			Devices _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDevicesEquals'
	 * 
	 * @param idDevices
	 */
	public static void findWhereIdDevicesEquals(int idDevices)
	{
		try {
			DevicesDao _dao = getDevicesDao();
			Devices _result[] = _dao.findWhereIdDevicesEquals(idDevices);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDevicesDao'
	 * 
	 * @return DevicesDao
	 */
	public static DevicesDao getDevicesDao()
	{
		return DevicesDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Devices dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdDevices() );
		System.out.println( buf.toString() );
	}

}
