/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import de.berlin.fu.data.dao.PropertyTypeDao;
import de.berlin.fu.data.dto.PropertyType;
import de.berlin.fu.data.exceptions.PropertyTypeDaoException;
import de.berlin.fu.data.factory.PropertyTypeDaoFactory;

public class PropertyTypeDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdPropertyTypeEquals(0);
		// findWhereNameEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			PropertyTypeDao _dao = getPropertyTypeDao();
			PropertyType _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdPropertyTypeEquals'
	 * 
	 * @param idPropertyType
	 */
	public static void findWhereIdPropertyTypeEquals(int idPropertyType)
	{
		try {
			PropertyTypeDao _dao = getPropertyTypeDao();
			PropertyType _result[] = _dao.findWhereIdPropertyTypeEquals(idPropertyType);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			PropertyTypeDao _dao = getPropertyTypeDao();
			PropertyType _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getPropertyTypeDao'
	 * 
	 * @return PropertyTypeDao
	 */
	public static PropertyTypeDao getPropertyTypeDao()
	{
		return PropertyTypeDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(PropertyType dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdPropertyType() );
		buf.append( ", " );
		buf.append( dto.getName() );
		System.out.println( buf.toString() );
	}

}
