/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dao;

import de.berlin.fu.data.dto.*;
import de.berlin.fu.data.exceptions.*;

public interface EventTypeDao
{
	/** 
	 * Inserts a new row in the EventType table.
	 */
	public EventTypePk insert(EventType dto) throws EventTypeDaoException;

	/** 
	 * Updates a single row in the EventType table.
	 */
	public void update(EventTypePk pk, EventType dto) throws EventTypeDaoException;

	/** 
	 * Deletes a single row in the EventType table.
	 */
	public void delete(EventTypePk pk) throws EventTypeDaoException;

	/** 
	 * Returns the rows from the EventType table that matches the specified primary-key value.
	 */
	public EventType findByPrimaryKey(EventTypePk pk) throws EventTypeDaoException;

	/** 
	 * Returns all rows from the EventType table that match the criteria 'idEventType = :idEventType'.
	 */
	public EventType findByPrimaryKey(int idEventType) throws EventTypeDaoException;

	/** 
	 * Returns all rows from the EventType table that match the criteria ''.
	 */
	public EventType[] findAll() throws EventTypeDaoException;

	/** 
	 * Returns all rows from the EventType table that match the criteria 'idEventType = :idEventType'.
	 */
	public EventType[] findWhereIdEventTypeEquals(int idEventType) throws EventTypeDaoException;

	/** 
	 * Returns all rows from the EventType table that match the criteria 'Name = :name'.
	 */
	public EventType[] findWhereNameEquals(String name) throws EventTypeDaoException;

	/** 
	 * Returns all rows from the EventType table that match the criteria 'Description = :description'.
	 */
	public EventType[] findWhereDescriptionEquals(String description) throws EventTypeDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the EventType table that match the specified arbitrary SQL statement
	 */
	public EventType[] findByDynamicSelect(String sql, Object[] sqlParams) throws EventTypeDaoException;

	/** 
	 * Returns all rows from the EventType table that match the specified arbitrary SQL statement
	 */
	public EventType[] findByDynamicWhere(String sql, Object[] sqlParams) throws EventTypeDaoException;

}
