/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Action table.
 */
public class ActionPk implements Serializable
{
	protected int idAction;

	/** 
	 * This attribute represents whether the primitive attribute idAction is null.
	 */
	protected boolean idActionNull;

	/** 
	 * Sets the value of idAction
	 */
	public void setIdAction(int idAction)
	{
		this.idAction = idAction;
	}

	/** 
	 * Gets the value of idAction
	 */
	public int getIdAction()
	{
		return idAction;
	}

	/**
	 * Method 'ActionPk'
	 * 
	 */
	public ActionPk()
	{
	}

	/**
	 * Method 'ActionPk'
	 * 
	 * @param idAction
	 */
	public ActionPk(final int idAction)
	{
		this.idAction = idAction;
	}

	/** 
	 * Sets the value of idActionNull
	 */
	public void setIdActionNull(boolean idActionNull)
	{
		this.idActionNull = idActionNull;
	}

	/** 
	 * Gets the value of idActionNull
	 */
	public boolean isIdActionNull()
	{
		return idActionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ActionPk)) {
			return false;
		}
		
		final ActionPk _cast = (ActionPk) _other;
		if (idAction != _cast.idAction) {
			return false;
		}
		
		if (idActionNull != _cast.idActionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idAction;
		_hashCode = 29 * _hashCode + (idActionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.ActionPk: " );
		ret.append( "idAction=" + idAction );
		return ret.toString();
	}

}
