/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;

public class Devices implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 2585811255858719587L;
	/** 
	 * This attribute maps to the column idDevices in the Devices table.
	 */
	protected int idDevices;

	/**
	 * Method 'Devices'
	 * 
	 */
	public Devices()
	{
	}

	/**
	 * Method 'getIdDevices'
	 * 
	 * @return int
	 */
	public int getIdDevices()
	{
		return idDevices;
	}

	/**
	 * Method 'setIdDevices'
	 * 
	 * @param idDevices
	 */
	public void setIdDevices(int idDevices)
	{
		this.idDevices = idDevices;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	@Override
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Devices)) {
			return false;
		}
		
		final Devices _cast = (Devices) _other;
		if (idDevices != _cast.idDevices) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	@Override
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDevices;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DevicesPk
	 */
	public DevicesPk createPk()
	{
		return new DevicesPk(idDevices);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	@Override
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.Devices: " );
		ret.append( "idDevices=" + idDevices );
		return ret.toString();
	}

}
