/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Devices table.
 */
public class DevicesPk implements Serializable
{
	protected int idDevices;

	/** 
	 * This attribute represents whether the primitive attribute idDevices is null.
	 */
	protected boolean idDevicesNull;

	/** 
	 * Sets the value of idDevices
	 */
	public void setIdDevices(int idDevices)
	{
		this.idDevices = idDevices;
	}

	/** 
	 * Gets the value of idDevices
	 */
	public int getIdDevices()
	{
		return idDevices;
	}

	/**
	 * Method 'DevicesPk'
	 * 
	 */
	public DevicesPk()
	{
	}

	/**
	 * Method 'DevicesPk'
	 * 
	 * @param idDevices
	 */
	public DevicesPk(final int idDevices)
	{
		this.idDevices = idDevices;
	}

	/** 
	 * Sets the value of idDevicesNull
	 */
	public void setIdDevicesNull(boolean idDevicesNull)
	{
		this.idDevicesNull = idDevicesNull;
	}

	/** 
	 * Gets the value of idDevicesNull
	 */
	public boolean isIdDevicesNull()
	{
		return idDevicesNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DevicesPk)) {
			return false;
		}
		
		final DevicesPk _cast = (DevicesPk) _other;
		if (idDevices != _cast.idDevices) {
			return false;
		}
		
		if (idDevicesNull != _cast.idDevicesNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDevices;
		_hashCode = 29 * _hashCode + (idDevicesNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.DevicesPk: " );
		ret.append( "idDevices=" + idDevices );
		return ret.toString();
	}

}
