/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;

public class EventtypeHasAction implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -7367364992551864633L;

	/** 
	 * This attribute maps to the column EventType_idEventType in the EventType_has_Action table.
	 */
	protected int eventtypeIdeventtype;

	/** 
	 * This attribute maps to the column Action_idAction in the EventType_has_Action table.
	 */
	protected int actionIdaction;

	/**
	 * Method 'EventtypeHasAction'
	 * 
	 */
	public EventtypeHasAction()
	{
	}

	/**
	 * Method 'getEventtypeIdeventtype'
	 * 
	 * @return int
	 */
	public int getEventtypeIdeventtype()
	{
		return eventtypeIdeventtype;
	}

	/**
	 * Method 'setEventtypeIdeventtype'
	 * 
	 * @param eventtypeIdeventtype
	 */
	public void setEventtypeIdeventtype(int eventtypeIdeventtype)
	{
		this.eventtypeIdeventtype = eventtypeIdeventtype;
	}

	/**
	 * Method 'getActionIdaction'
	 * 
	 * @return int
	 */
	public int getActionIdaction()
	{
		return actionIdaction;
	}

	/**
	 * Method 'setActionIdaction'
	 * 
	 * @param actionIdaction
	 */
	public void setActionIdaction(int actionIdaction)
	{
		this.actionIdaction = actionIdaction;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	@Override
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EventtypeHasAction)) {
			return false;
		}
		
		final EventtypeHasAction _cast = (EventtypeHasAction) _other;
		if (eventtypeIdeventtype != _cast.eventtypeIdeventtype) {
			return false;
		}
		
		if (actionIdaction != _cast.actionIdaction) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	@Override
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + eventtypeIdeventtype;
		_hashCode = 29 * _hashCode + actionIdaction;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EventtypeHasActionPk
	 */
	public EventtypeHasActionPk createPk()
	{
		return new EventtypeHasActionPk(eventtypeIdeventtype, actionIdaction);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	@Override
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.EventtypeHasAction: " );
		ret.append( "eventtypeIdeventtype=" + eventtypeIdeventtype );
		ret.append( ", actionIdaction=" + actionIdaction );
		return ret.toString();
	}

}
