/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;

/** 
 * This class represents the primary key of the Event table.
 */
public class EventPk implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 2801000060045454439L;

	protected int idEvent;

	protected int eventtypeIdeventtype;

	/** 
	 * This attribute represents whether the primitive attribute idEvent is null.
	 */
	protected boolean idEventNull;

	/** 
	 * This attribute represents whether the primitive attribute eventtypeIdeventtype is null.
	 */
	protected boolean eventtypeIdeventtypeNull;

	/** 
	 * Sets the value of idEvent
	 */
	public void setIdEvent(int idEvent)
	{
		this.idEvent = idEvent;
	}

	/** 
	 * Gets the value of idEvent
	 */
	public int getIdEvent()
	{
		return idEvent;
	}

	/** 
	 * Sets the value of eventtypeIdeventtype
	 */
	public void setEventtypeIdeventtype(int eventtypeIdeventtype)
	{
		this.eventtypeIdeventtype = eventtypeIdeventtype;
	}

	/** 
	 * Gets the value of eventtypeIdeventtype
	 */
	public int getEventtypeIdeventtype()
	{
		return eventtypeIdeventtype;
	}

	/**
	 * Method 'EventPk'
	 * 
	 */
	public EventPk()
	{
	}

	/**
	 * Method 'EventPk'
	 * 
	 * @param idEvent
	 * @param eventtypeIdeventtype
	 */
	public EventPk(final int idEvent, final int eventtypeIdeventtype)
	{
		this.idEvent = idEvent;
		this.eventtypeIdeventtype = eventtypeIdeventtype;
	}

	/** 
	 * Sets the value of idEventNull
	 */
	public void setIdEventNull(boolean idEventNull)
	{
		this.idEventNull = idEventNull;
	}

	/** 
	 * Gets the value of idEventNull
	 */
	public boolean isIdEventNull()
	{
		return idEventNull;
	}

	/** 
	 * Sets the value of eventtypeIdeventtypeNull
	 */
	public void setEventtypeIdeventtypeNull(boolean eventtypeIdeventtypeNull)
	{
		this.eventtypeIdeventtypeNull = eventtypeIdeventtypeNull;
	}

	/** 
	 * Gets the value of eventtypeIdeventtypeNull
	 */
	public boolean isEventtypeIdeventtypeNull()
	{
		return eventtypeIdeventtypeNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	@Override
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EventPk)) {
			return false;
		}
		
		final EventPk _cast = (EventPk) _other;
		if (idEvent != _cast.idEvent) {
			return false;
		}
		
		if (eventtypeIdeventtype != _cast.eventtypeIdeventtype) {
			return false;
		}
		
		if (idEventNull != _cast.idEventNull) {
			return false;
		}
		
		if (eventtypeIdeventtypeNull != _cast.eventtypeIdeventtypeNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	@Override
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idEvent;
		_hashCode = 29 * _hashCode + eventtypeIdeventtype;
		_hashCode = 29 * _hashCode + (idEventNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (eventtypeIdeventtypeNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	@Override
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.EventPk: " );
		ret.append( "idEvent=" + idEvent );
		ret.append( ", eventtypeIdeventtype=" + eventtypeIdeventtype );
		return ret.toString();
	}

}
