/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the EventType table.
 */
public class EventTypePk implements Serializable
{
	protected int idEventType;

	/** 
	 * This attribute represents whether the primitive attribute idEventType is null.
	 */
	protected boolean idEventTypeNull;

	/** 
	 * Sets the value of idEventType
	 */
	public void setIdEventType(int idEventType)
	{
		this.idEventType = idEventType;
	}

	/** 
	 * Gets the value of idEventType
	 */
	public int getIdEventType()
	{
		return idEventType;
	}

	/**
	 * Method 'EventTypePk'
	 * 
	 */
	public EventTypePk()
	{
	}

	/**
	 * Method 'EventTypePk'
	 * 
	 * @param idEventType
	 */
	public EventTypePk(final int idEventType)
	{
		this.idEventType = idEventType;
	}

	/** 
	 * Sets the value of idEventTypeNull
	 */
	public void setIdEventTypeNull(boolean idEventTypeNull)
	{
		this.idEventTypeNull = idEventTypeNull;
	}

	/** 
	 * Gets the value of idEventTypeNull
	 */
	public boolean isIdEventTypeNull()
	{
		return idEventTypeNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EventTypePk)) {
			return false;
		}
		
		final EventTypePk _cast = (EventTypePk) _other;
		if (idEventType != _cast.idEventType) {
			return false;
		}
		
		if (idEventTypeNull != _cast.idEventTypeNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idEventType;
		_hashCode = 29 * _hashCode + (idEventTypeNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.EventTypePk: " );
		ret.append( "idEventType=" + idEventType );
		return ret.toString();
	}

}
