/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the PropertyType table.
 */
public class PropertyTypePk implements Serializable
{
	protected int idPropertyType;

	/** 
	 * This attribute represents whether the primitive attribute idPropertyType is null.
	 */
	protected boolean idPropertyTypeNull;

	/** 
	 * Sets the value of idPropertyType
	 */
	public void setIdPropertyType(int idPropertyType)
	{
		this.idPropertyType = idPropertyType;
	}

	/** 
	 * Gets the value of idPropertyType
	 */
	public int getIdPropertyType()
	{
		return idPropertyType;
	}

	/**
	 * Method 'PropertyTypePk'
	 * 
	 */
	public PropertyTypePk()
	{
	}

	/**
	 * Method 'PropertyTypePk'
	 * 
	 * @param idPropertyType
	 */
	public PropertyTypePk(final int idPropertyType)
	{
		this.idPropertyType = idPropertyType;
	}

	/** 
	 * Sets the value of idPropertyTypeNull
	 */
	public void setIdPropertyTypeNull(boolean idPropertyTypeNull)
	{
		this.idPropertyTypeNull = idPropertyTypeNull;
	}

	/** 
	 * Gets the value of idPropertyTypeNull
	 */
	public boolean isIdPropertyTypeNull()
	{
		return idPropertyTypeNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PropertyTypePk)) {
			return false;
		}
		
		final PropertyTypePk _cast = (PropertyTypePk) _other;
		if (idPropertyType != _cast.idPropertyType) {
			return false;
		}
		
		if (idPropertyTypeNull != _cast.idPropertyTypeNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idPropertyType;
		_hashCode = 29 * _hashCode + (idPropertyTypeNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.PropertyTypePk: " );
		ret.append( "idPropertyType=" + idPropertyType );
		return ret.toString();
	}

}
