/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;
import java.util.Date;

public class Property implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -5464859885328834312L;

	/**
	 * This attribute maps to the column idProperty in the Property table.
	 */
	protected int idProperty;

	/**
	 * This attribute maps to the column PropertyType_idPropertyType in the
	 * Property table.
	 */
	protected int propertytypeIdpropertytype;

	/**
	 * This attribute maps to the column Sensor_idSensor in the Property table.
	 */
	protected String sensorIdsensor;

	/**
	 * This attribute maps to the column Value in the Property table.
	 */
	protected double value;

	/**
	 * This attribute represents whether the primitive attribute value is null.
	 */
	protected boolean valueNull = true;

	/**
	 * This attribute maps to the column Timestamp in the Property table.
	 */
	protected Date timestamp;

	/**
	 * Method 'Property'
	 * 
	 */
	public Property() {
	}

	/**
	 * Method 'getIdProperty'
	 * 
	 * @return int
	 */
	public int getIdProperty() {
		return idProperty;
	}

	/**
	 * Method 'setIdProperty'
	 * 
	 * @param idProperty
	 */
	public void setIdProperty(int idProperty) {
		this.idProperty = idProperty;
	}

	/**
	 * Method 'getPropertytypeIdpropertytype'
	 * 
	 * @return int
	 */
	public int getPropertytypeIdpropertytype() {
		return propertytypeIdpropertytype;
	}

	/**
	 * Method 'setPropertytypeIdpropertytype'
	 * 
	 * @param propertytypeIdpropertytype
	 */
	public void setPropertytypeIdpropertytype(int propertytypeIdpropertytype) {
		this.propertytypeIdpropertytype = propertytypeIdpropertytype;
	}

	/**
	 * Method 'getSensorIdsensor'
	 * 
	 * @return String
	 */
	public String getSensorIdsensor() {
		return sensorIdsensor;
	}

	/**
	 * Method 'setSensorIdsensor'
	 * 
	 * @param sensorIdsensor
	 */
	public void setSensorIdsensor(String sensorIdsensor) {
		this.sensorIdsensor = sensorIdsensor;
	}

	/**
	 * Method 'getValue'
	 * 
	 * @return double
	 */
	public double getValue() {
		return value;
	}

	/**
	 * Method 'setValue'
	 * 
	 * @param value
	 */
	public void setValue(double value) {
		this.value = value;
		this.valueNull = false;
	}

	/**
	 * Method 'setValueNull'
	 * 
	 * @param value
	 */
	public void setValueNull(boolean value) {
		this.valueNull = value;
	}

	/**
	 * Method 'isValueNull'
	 * 
	 * @return boolean
	 */
	public boolean isValueNull() {
		return valueNull;
	}

	/**
	 * Method 'getTimestamp'
	 * 
	 * @return Date
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * Method 'setTimestamp'
	 * 
	 * @param timestamp
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other) {
		if (_other == null) {
			return false;
		}

		if (_other == this) {
			return true;
		}

		if (!(_other instanceof Property)) {
			return false;
		}

		final Property _cast = (Property) _other;
		if (idProperty != _cast.idProperty) {
			return false;
		}

		if (propertytypeIdpropertytype != _cast.propertytypeIdpropertytype) {
			return false;
		}

		if (sensorIdsensor == null ? _cast.sensorIdsensor != sensorIdsensor
				: !sensorIdsensor.equals(_cast.sensorIdsensor)) {
			return false;
		}

		if (value != _cast.value) {
			return false;
		}

		if (valueNull != _cast.valueNull) {
			return false;
		}

		if (timestamp == null ? _cast.timestamp != timestamp : !timestamp
				.equals(_cast.timestamp)) {
			return false;
		}

		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode() {
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProperty;
		_hashCode = 29 * _hashCode + propertytypeIdpropertytype;
		if (sensorIdsensor != null) {
			_hashCode = 29 * _hashCode + sensorIdsensor.hashCode();
		}
		// TODO hotfix
		// long temp_value = Double.doubleToLongBits(value);
		long temp_value = Long.valueOf(String.valueOf(value));
		_hashCode = 29 * _hashCode + (int) (temp_value ^ (temp_value >>> 32));
		_hashCode = 29 * _hashCode + (valueNull ? 1 : 0);
		if (timestamp != null) {
			_hashCode = 29 * _hashCode + timestamp.hashCode();
		}

		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PropertyPk
	 */
	public PropertyPk createPk() {
		return new PropertyPk(idProperty, propertytypeIdpropertytype,
				sensorIdsensor);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer ret = new StringBuffer();
		ret.append("de.berlin.fu.data.dto.Property: ");
		ret.append("idProperty=" + idProperty);
		ret.append(", propertytypeIdpropertytype=" + propertytypeIdpropertytype);
		ret.append(", sensorIdsensor=" + sensorIdsensor);
		ret.append(", value=" + value);
		ret.append(", timestamp=" + timestamp);
		return ret.toString();
	}

}
