/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;

public class PropertyType implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -6140088813987225199L;

	/** 
	 * This attribute maps to the column idPropertyType in the PropertyType table.
	 */
	protected int idPropertyType;

	/** 
	 * This attribute maps to the column Name in the PropertyType table.
	 */
	protected String name;

	/**
	 * Method 'PropertyType'
	 * 
	 */
	public PropertyType()
	{
	}

	/**
	 * Method 'getIdPropertyType'
	 * 
	 * @return int
	 */
	public int getIdPropertyType()
	{
		return idPropertyType;
	}

	/**
	 * Method 'setIdPropertyType'
	 * 
	 * @param idPropertyType
	 */
	public void setIdPropertyType(int idPropertyType)
	{
		this.idPropertyType = idPropertyType;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	@Override
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PropertyType)) {
			return false;
		}
		
		final PropertyType _cast = (PropertyType) _other;
		if (idPropertyType != _cast.idPropertyType) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	@Override
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idPropertyType;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PropertyTypePk
	 */
	public PropertyTypePk createPk()
	{
		return new PropertyTypePk(idPropertyType);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	@Override
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.PropertyType: " );
		ret.append( "idPropertyType=" + idPropertyType );
		ret.append( ", name=" + name );
		return ret.toString();
	}

}
