/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import de.berlin.fu.data.dao.*;
import de.berlin.fu.data.factory.*;
import de.berlin.fu.data.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class SensorHasPropertytype implements Serializable
{
	/** 
	 * This attribute maps to the column Sensor_idSensor in the Sensor_has_PropertyType table.
	 */
	protected String sensorIdsensor;

	/** 
	 * This attribute maps to the column PropertyType_idPropertyType in the Sensor_has_PropertyType table.
	 */
	protected int propertytypeIdpropertytype;

	/**
	 * Method 'SensorHasPropertytype'
	 * 
	 */
	public SensorHasPropertytype()
	{
	}

	/**
	 * Method 'getSensorIdsensor'
	 * 
	 * @return String
	 */
	public String getSensorIdsensor()
	{
		return sensorIdsensor;
	}

	/**
	 * Method 'setSensorIdsensor'
	 * 
	 * @param sensorIdsensor
	 */
	public void setSensorIdsensor(String sensorIdsensor)
	{
		this.sensorIdsensor = sensorIdsensor;
	}

	/**
	 * Method 'getPropertytypeIdpropertytype'
	 * 
	 * @return int
	 */
	public int getPropertytypeIdpropertytype()
	{
		return propertytypeIdpropertytype;
	}

	/**
	 * Method 'setPropertytypeIdpropertytype'
	 * 
	 * @param propertytypeIdpropertytype
	 */
	public void setPropertytypeIdpropertytype(int propertytypeIdpropertytype)
	{
		this.propertytypeIdpropertytype = propertytypeIdpropertytype;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SensorHasPropertytype)) {
			return false;
		}
		
		final SensorHasPropertytype _cast = (SensorHasPropertytype) _other;
		if (sensorIdsensor == null ? _cast.sensorIdsensor != sensorIdsensor : !sensorIdsensor.equals( _cast.sensorIdsensor )) {
			return false;
		}
		
		if (propertytypeIdpropertytype != _cast.propertytypeIdpropertytype) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (sensorIdsensor != null) {
			_hashCode = 29 * _hashCode + sensorIdsensor.hashCode();
		}
		
		_hashCode = 29 * _hashCode + propertytypeIdpropertytype;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SensorHasPropertytypePk
	 */
	public SensorHasPropertytypePk createPk()
	{
		return new SensorHasPropertytypePk(sensorIdsensor, propertytypeIdpropertytype);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.SensorHasPropertytype: " );
		ret.append( "sensorIdsensor=" + sensorIdsensor );
		ret.append( ", propertytypeIdpropertytype=" + propertytypeIdpropertytype );
		return ret.toString();
	}

}
