/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Sensor table.
 */
public class SensorPk implements Serializable
{
	protected String idSensor;

	/** 
	 * Sets the value of idSensor
	 */
	public void setIdSensor(String idSensor)
	{
		this.idSensor = idSensor;
	}

	/** 
	 * Gets the value of idSensor
	 */
	public String getIdSensor()
	{
		return idSensor;
	}

	/**
	 * Method 'SensorPk'
	 * 
	 */
	public SensorPk()
	{
	}

	/**
	 * Method 'SensorPk'
	 * 
	 * @param idSensor
	 */
	public SensorPk(final String idSensor)
	{
		this.idSensor = idSensor;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SensorPk)) {
			return false;
		}
		
		final SensorPk _cast = (SensorPk) _other;
		if (idSensor == null ? _cast.idSensor != idSensor : !idSensor.equals( _cast.idSensor )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idSensor != null) {
			_hashCode = 29 * _hashCode + idSensor.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.SensorPk: " );
		ret.append( "idSensor=" + idSensor );
		return ret.toString();
	}

}
