/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package de.berlin.fu.data.dto;

import de.berlin.fu.data.dao.*;
import de.berlin.fu.data.factory.*;
import de.berlin.fu.data.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class SensorHasTrigger implements Serializable
{
	/** 
	 * This attribute maps to the column Sensor_idSensor in the Sensor_has_Trigger table.
	 */
	protected String sensorIdsensor;

	/** 
	 * This attribute maps to the column Trigger_idTrigger in the Sensor_has_Trigger table.
	 */
	protected int triggerIdtrigger;

	/**
	 * Method 'SensorHasTrigger'
	 * 
	 */
	public SensorHasTrigger()
	{
	}

	/**
	 * Method 'getSensorIdsensor'
	 * 
	 * @return String
	 */
	public String getSensorIdsensor()
	{
		return sensorIdsensor;
	}

	/**
	 * Method 'setSensorIdsensor'
	 * 
	 * @param sensorIdsensor
	 */
	public void setSensorIdsensor(String sensorIdsensor)
	{
		this.sensorIdsensor = sensorIdsensor;
	}

	/**
	 * Method 'getTriggerIdtrigger'
	 * 
	 * @return int
	 */
	public int getTriggerIdtrigger()
	{
		return triggerIdtrigger;
	}

	/**
	 * Method 'setTriggerIdtrigger'
	 * 
	 * @param triggerIdtrigger
	 */
	public void setTriggerIdtrigger(int triggerIdtrigger)
	{
		this.triggerIdtrigger = triggerIdtrigger;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SensorHasTrigger)) {
			return false;
		}
		
		final SensorHasTrigger _cast = (SensorHasTrigger) _other;
		if (sensorIdsensor == null ? _cast.sensorIdsensor != sensorIdsensor : !sensorIdsensor.equals( _cast.sensorIdsensor )) {
			return false;
		}
		
		if (triggerIdtrigger != _cast.triggerIdtrigger) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (sensorIdsensor != null) {
			_hashCode = 29 * _hashCode + sensorIdsensor.hashCode();
		}
		
		_hashCode = 29 * _hashCode + triggerIdtrigger;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SensorHasTriggerPk
	 */
	public SensorHasTriggerPk createPk()
	{
		return new SensorHasTriggerPk(sensorIdsensor, triggerIdtrigger);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "de.berlin.fu.data.dto.SensorHasTrigger: " );
		ret.append( "sensorIdsensor=" + sensorIdsensor );
		ret.append( ", triggerIdtrigger=" + triggerIdtrigger );
		return ret.toString();
	}

}
